version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_DB: api_schema
          POSTGRES_USER: api_user
          POSTGRES_PASSWORD: my-secret-password

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip3 install pipenv
            pipenv install

      - run:
          name: Run the Tests
          command: |
            pipenv run python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports


